config/routes.rb
Rails.application.routes.draw do
  resources :gift_statuses, only: [:index, :create, :find]
  get '/promotion', to: 'gift_statuses#index'
  post '/promotion', to: 'gift_statuses#create'
  post '/find_promotion', to: 'gift_statuses#find'
  resources :products, only: [:index, :new, :create, :update] do 
  	collection do 
  	  post :import
  	end
  end
  resources :users, only: [:index, :new, :create, :update] do 
    collection do 
      post :import_resellers
    end
  end
  resources :customers, only: [:index, :show, :update] do 
  	collection do 
  	  post :import
  	  post :generate_code
      get  :export
      post :approve_all
      post :import_sms
  	end
  end
  resources :campaigns, only: [:index, :new, :create, :edit, :update, :show] do 
    collection do 
      get :cost_report
      get :time_report
    end
  end
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'home#index'
  get '404', :to => 'application#page_not_found'
end

app/models/user.rb
class User < ApplicationRecord  
  include Authenticable, 
  		  UserScope, 
  		  UserValidator
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin
  before_action :require_user, only: [:update]

  def index
  	@resellers = paginate User.reseller
  end

  def new
  end

  def update
    command = UpdateRecord.call(user, user_params)
    if command.success?
      redirect_to users_path, success: "Updated successfully"
    else
      redirect_to users_path, error: "Update error"
    end
  end

  def create
  end

  def import_resellers
  	import_command = BatchFileImportResellers.call(params[:file])
  	if import_command.success?
  	  redirect_to users_path, notice: "Users successfully imported"
  	else
  	  redirect_to users_path, danger: import_command.errors.to_s
  	end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone, :location)
  end

  def require_user
    @user ||= User.find_by_id(params[:id])
    redirect_to users_path, error: "User not found" and return unless @user
  end

  def user
    @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(user, html: { class: 'form-horizontal' }, method: :put) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :location %>
  <%= f.submit :Update, class: "btn btn-primary" %>
<% end %>

app/views/users/_modal_form.html.erb
<div class="modal fade" id="form-modal-<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>

                    </button>
                     <h4 class="modal-title" id="myModalLabel">Update User <%= user.name %></h4>

                </div>
                <div class="modal-body">
                    <%= render partial: "users/form", locals: { user: user } %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/_resellers.html.erb
<table class="table table-bordered table-condensed table-striped" data-toggle="table">
    <thead>
        <tr>
            <th data-field="id">ID</th>
            <th data-field="name">Name</th>
            <th data-field="email">Email</th>
            <th data-field="phone">Phone</th>
            <th data-field="end_time">Location</th>
            <th data-field="edit">Edit</th>
        </tr>
    </thead>
    <tbody>
    <% resellers.each do |reseller| %>
        <tr>
        <td><%= reseller.id %> </td>
        <td><%= reseller.name %></td>
        <td><%= reseller.email %></td>
        <td><%= reseller.phone %></td>
        <td><%= reseller.location %></td>
        <td><i class="fa fa-pencil-square-o" aria-hidden="true" data-toggle="modal" data-target="#form-modal-<%= reseller.id %>"></i></td>
        <%= render partial: "users/modal_form", locals: { user: reseller } %>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate resellers %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= form_tag import_resellers_users_path, multipart: true, class: "form-horizontal" do %>
	<%= file_field_tag :file %>
	<br/>
	<%= submit_tag "Import Resellers" %>
<% end %>
<hr/>
<%= render partial: "users/resellers", locals: { resellers: @resellers } %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>