config/routes.rb
Rails.application.routes.draw do
  resources :gift_statuses, only: [:index, :create, :find]
  get '/promotion', to: 'gift_statuses#index'
  post '/promotion', to: 'gift_statuses#create'
  post '/find_promotion', to: 'gift_statuses#find'
  resources :products, only: [:index, :new, :create, :update] do 
  	collection do 
  	  post :import
  	end
  end
  resources :users, only: [:index, :new, :create, :update] do 
    collection do 
      post :import_resellers
    end
  end
  resources :customers, only: [:index, :show, :update] do 
  	collection do 
  	  post :import
  	  post :generate_code
      get  :export
      post :approve_all
      post :import_sms
  	end
  end
  resources :campaigns, only: [:index, :new, :create, :edit, :update, :show] do 
    collection do 
      get :cost_report
      get :time_report
    end
  end
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'home#index'
  get '404', :to => 'application#page_not_found'
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  include CampaignValidator, 
  		  CampaignAssociation, 
  		  CampaignScope
end

app/models/campaign_form.rb
class CampaignForm < BaseForm
  
  attr_accessor :name, :content, :start_time, :end_time, :location, :product_count, :product_id

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
  validates :product_count, presence: true, numericality: { greater_than: 0 }
  validates :product_id, presence: true

  def save
  	if valid?
  	  product = Product.find_by_id(product_id)
      start_time = DateTime.parse(start_time) rescue Time.current
      end_time = DateTime.parse(end_time) rescue Time.current
  	  if product
  	  	command = CreateCampaign.call(
  	  	  name, content, start_time, end_time, location, product_count, product
  	  	)
  	  	return command.result if command.success?
  	  	append_errors command
  	  else
  	  	errors.add :campaign_form, "Product not found"
  	  end
  	end
  end
end

app/controllers/api/campaigns_controller.rb
module Api
  class CampaignsController < BaseController
  	def index
  	  present CampaignsPresenter.new(Campaign.page(params[:page]).per(params[:per_page]))
  	end
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :require_admin
  before_action :require_campaign, only: [:show, :edit, :update]  
  before_action :require_products, only: [:new]

  def index    
    query = CampaignSearchQuery.new(params[:date], params[:city], params[:product_name])
    @resources = paginate(query.render)
  end

  def new
    @campaign = CampaignForm.new
  end

  def create
    @campaign = CampaignForm.new(campaign_params)
    if @campaign.save
      redirect_to campaigns_path, success: "Campaign created"
    else
      render :new
    end
  end

  api :GET, '/campaigns/:id'
  def show
    @campaign_customers = paginate @campaign.campaign_customers
  end

  def edit
  end

  def update
    command = UpdateRecord.call(campaign, update_campaign_params)
    if command.success?
      redirect_to campaigns_path, success: "Updated successfully"
    else
      redirect_to campaigns_path, error: "Update error"
    end
  end

  def cost_report
    query = CampaignCostReportQuery.new(params[:date1], params[:date2])
    @resources = paginate(query.render)
  end

  def time_report
    query = CampaignTimeReportQuery.new
    @resources = paginate(query.render)
  end

  private

  def campaign_params
    params.require(:campaign_form).permit(
      :name, 
      :content, 
      :start_time, 
      :end_time, 
      :location, 
      :product_count,
      :product_id
    )
  end

  def update_campaign_params
    params.require(:campaign).permit(
      :name,
      :content,
      :location,
      :product_count
    )
  end

  def require_campaign
    @campaign ||= Campaign.find_by_id(params[:id])
    redirect_to root_path and return unless @campaign
  end

  def require_products
    @products ||= Product.all
  end

  def campaign
    @campaign
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_common.html.erb
<div class="well">
  <%= link_to "New Product Campaign", new_campaign_path, class: "btn btn-default" %>
  <%= link_to "Phân tích hiệu quả chiến dịch", cost_report_campaigns_path, class: "btn btn-default" %>
  <%= link_to "Phân tích hiệu quả theo thời gian", time_report_campaigns_path, class: "btn btn-default" %>
</div>

app/views/campaigns/_form.html.erb
<%= simple_form_for(:campaign, url: campaign_path(campaign[:id]), html: { class: 'form-horizontal' }, method: :put) do |f| %>
  <%= f.input :name, input_html: { value: campaign[:name] } %>
  <%= f.input :content, input_html: { value: campaign[:content] }  %>
  <%= f.input :location, input_html: { value: campaign[:city] }  %>
  <%= f.input :product_count, input_html: { value: campaign[:product_count] }  %>
  <%= f.submit :Update, class: "btn btn-primary" %>
<% end %>

app/views/campaigns/_modal_form.html.erb
<div class="modal fade" id="form-modal-<%= campaign[:id] %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>

                    </button>
                     <h4 class="modal-title" id="myModalLabel">Update Campaign <%= campaign[:name] %></h4>

                </div>
                <div class="modal-body">
                    <%= render partial: "campaigns/form", locals: { campaign: campaign } %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
$( "#form-modal-<%= campaign[:id] %>" ).on('shown', function(){
  $("input#campaign_form_location").geocomplete();
  $(".select2").select2();
});
</script>

app/views/campaigns/_panel.html.erb
<div class="well">
  <div class="row">
  	<div class="col-md-3">
	  <%= form_tag import_customers_path, multipart: true, class: "form-horizontal" do %>
	  	<%= hidden_field_tag :campaign_id, @campaign.id %>
	  	<%= file_field_tag :file %>
	  	<br/>
	  	<%= submit_tag "Import Customers" %>
	  <% end %>
  	</div>

  	<div class="col-md-3">
	  <%= form_tag generate_code_customers_path, multipart: true do %>
	  	<%= hidden_field_tag :campaign_id, @campaign.id %>
	  	<%= submit_tag "Generate Codes" %>
	  <% end %>
	  <br/>

	  <%= form_tag approve_all_customers_path do %>
	  	<%= hidden_field_tag :campaign_id, @campaign.id %>
	  	<%= submit_tag "Approve all" %>
	  <% end %>

	  <br/>

	  <%= form_tag export_customers_path(format: :xlsx), method: :get do %>
	  	<%= hidden_field_tag :campaign_id, @campaign.id %>
	  	<%= submit_tag "Export" %>
	  <% end %>
  	</div>

  	<div class="col-md-3">
  	  <%= form_tag import_sms_customers_path, multipart: true, class: "form-horizontal" do %>
	  	<%= hidden_field_tag :campaign_id, @campaign.id %>
	  	<%= file_field_tag :file %>
	  	<br/>
	  	<%= submit_tag "Import Sms" %>
	  <% end %>
  	</div>
  </div>
</div>

app/views/campaigns/_search.html.erb
<%= form_tag(campaigns_path, :method => "get", id: "search-form", class: "form-horizontal") do %>
  <div class="row">
  	<div class="col-md-3">
	<input type="text" name="city" class='form-control' placeholder="City" value = <%= params[:city].present? ? params[:city] : "" %> >
	</div>
	<div class="col-md-3">
		<input type="text" data-provide='datepicker' class='form-control' name="date" placeholder="Choose a date" value = <%= params[:date].present? ? params[:date] : "" %> >
	</div>
	<div class="col-md-3">
		<input type="text" name="product_name" class='form-control' placeholder="Product name" value = <%= params[:product_name].present? ? params[:product_name] : "" %> >
	</div>
	<div class="col-md-3">
    	<%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/campaigns/cost_report.html.erb
<%= render "campaigns/common" %>

<h2>Campaigns Cost Report:</h2>

<table class="table table-bordered table-condensed table-striped" data-toggle="table">
    <thead>
        <tr>
            <th data-field="name">Campaign Name</th>
            <th data-field="total">Total</th>
            <th data-field="customers_count">Customers Count</th>
        </tr>
    </thead>
    <tbody>
    <% @resources.each do |resource| %>
        <tr>
        <td><%= link_to resource[:campaign_name], campaign_path(resource[:campaign_id]) %></td>
        <td><%= resource[:total] %></td>
        <td><%= resource[:customers_count] %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate @resources %>

app/views/campaigns/create.html.erb
<h1>Campaigns#create</h1>
<p>Find me in app/views/campaigns/create.html.erb</p>

app/views/campaigns/edit.html.erb
<h1>Campaigns#edit</h1>
<p>Find me in app/views/campaigns/edit.html.erb</p>

app/views/campaigns/index.html.erb
<%= render "campaigns/common" %>
<%= render "campaigns/search" %>
<hr/><hr/>
<h1>Campaigns</h1>
<table class="table table-bordered table-condensed table-striped" data-toggle="table">
    <thead>
        <tr>
            <th data-field="id">ID</th>
            <th data-field="name">Name</th>
            <th data-field="content">Content</th>
            <th data-field="start_time">Start Time</th>
            <th data-field="end_time">End Time</th>
            <th data-field="location">City</th>
            <th data-field="product_count">Promotion</th>
            <th data-field="product_name">Product Name</th>
            <th data-field="edit">Edit</th>
        </tr>
    </thead>
    <tbody>
    <% @resources.each do |campaign| %>
        <tr>
        <td><%= link_to campaign[:name], campaign_path(campaign[:id]) %> </td>
        <td><%= campaign[:name] %></td>
        <td><%= campaign[:content] %></td>
        <td><%= campaign[:start_time] %></td>
        <td><%= campaign[:end_time] %></td>
        <td><%= campaign[:city] %></td>
        <td><%= campaign[:product_count] %></td>
        <td><%= campaign[:product_name] %></td>
        <td><i class="fa fa-pencil-square-o" aria-hidden="true" data-toggle="modal" data-target="#form-modal-<%= campaign[:id] %>"></i></td>
        <%= render partial: "campaigns/modal_form", locals: { campaign: campaign } %>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate @resources %>
<script>
  $("input#campaign_form_location").geocomplete();
  $(".select2").select2();
</script>

app/views/campaigns/new.html.erb
<%= render "campaigns/common" %>
<%= simple_form_for(@campaign, url: campaigns_path,  html: { class: 'form-horizontal' }) do |f| %>
  <div class="row">
	  <div class="col-md-3">
	  	<%= f.input :name %>
	  </div>
	  <div class="col-md-8 col-md-offset-1">
	  	<%= f.input :content %>
	  </div>
  </div>
  <div class="row">
	  <div class="col-md-3">
		  <%= f.input :start_time, as: :string, input_html: { class: "datepicker" } %>
	</div>
	<div class="col-md-3 col-md-offset-1">
  		<%= f.input :end_time, as: :string, input_html: { class: "datepicker" } %>
  	</div>
  </div>
  <div class="row">
	<div class="col-md-3">
  		<%= f.input :location %>
  	</div>
  	<div class="col-md-2 col-md-offset-1">
  		<%= f.input :product_count %>
  	</div>  	
  </div>
  <div class="row">
  	<div class="col-md-6">
  		<%= f.input :product_id, collection: @products, input_html: { class: "select2" } %>
  	</div>
	</div>
	<%= f.submit :Create, class: "btn btn-primary" %>  		
  </div>
  
  
<% end %>
<script>
	$("input#campaign_form_location").geocomplete();
	$(".select2").select2();
</script>

app/views/campaigns/show.html.erb
<%= render "campaigns/common" %>
<%= @campaign.name %>

<%= render "campaigns/panel" %>

<div class="row">
<h3>Campaign's Customers</h3>

<%= render partial: "campaign_customers/index", locals: { campaign_customers: @campaign_customers } %>

</div>

app/views/campaigns/time_report.html.erb
<%= render "campaigns/common" %>

<h2>Campaigns Cost Report:</h2>

<table class="table table-bordered table-condensed table-striped" data-toggle="table">
    <thead>
        <tr>
            <th data-field="name">Campaign ID</th>
            <th data-field="month">Month</th>
            <th data-field="customers_count">Customers Count</th>
            <th data-field="product_name">Product Name</th>
            <th data-field="product_count">Products Count</th>
        </tr>
    </thead>
    <tbody>
    <% @resources.each do |resource| %>
        <tr>
        <td><%= link_to resource[:campaign_id], campaign_path(resource[:campaign_id]) %></td>
        <td><%= resource[:month] %></td>
        <td><%= resource[:customer_count] %></td>
        <td><%= resource[:product_name] %></td>
        <td><%= resource[:product_count] %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate @resources %>

app/views/campaigns/update.html.erb
<h1>Campaigns#update</h1>
<p>Find me in app/views/campaigns/update.html.erb</p>