config/routes.rb
Rails.application.routes.draw do
  resources :gift_statuses, only: [:index, :create, :find]
  get '/promotion', to: 'gift_statuses#index'
  post '/promotion', to: 'gift_statuses#create'
  post '/find_promotion', to: 'gift_statuses#find'
  resources :products, only: [:index, :new, :create, :update] do 
  	collection do 
  	  post :import
  	end
  end
  resources :users, only: [:index, :new, :create, :update] do 
    collection do 
      post :import_resellers
    end
  end
  resources :customers, only: [:index, :show, :update] do 
  	collection do 
  	  post :import
  	  post :generate_code
      get  :export
      post :approve_all
      post :import_sms
  	end
  end
  resources :campaigns, only: [:index, :new, :create, :edit, :update, :show] do 
    collection do 
      get :cost_report
      get :time_report
    end
  end
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'home#index'
  get '404', :to => 'application#page_not_found'
end

app/models/product.rb
class Product < ApplicationRecord
  include ProductValidator, 
  		  ProductAssociation
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_admin
  before_action :require_product, only: [:update]

  def index
  	@resources = paginate(Product)
    query = CampaignProductsQuery.new(params[:campaign_name], params[:date1], params[:date2])
    favorite_products_query = FavoriteProductsQuery.new(params[:date1], params[:date2])
    @campaign_products = paginate(query.render)
    @favorite_products = paginate(favorite_products_query.render)
  end

  def new
  end

  def update
    command = UpdateRecord.call(product, product_params)
    if command.success?
      redirect_to products_path, success: "Updated successfully"
    else
      redirect_to products_path, error: "Update error"
    end
  end

  def create
  end

  def import
  	command = FileImportProducts.call(params[:file])
  	if command.success?
  	  redirect_to products_path, success: "Products uploaded"
  	else
  	  redirect_to products_path, error: "There is error when importing"
  	end
  end

  private

  def product_params
    params.require(:product).permit(:name, :code, :price, :unit)
  end

  def require_product
    @product ||= Product.find_by_id(params[:id])
    redirect_to products_path, error: "Product not found" and return unless @product
  end

  def product
    @product
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_campaign_products.html.erb
<table class="table table-bordered table-condensed table-striped" data-toggle="table">
    <thead>
        <tr>
            <th data-field="name">Campaign Name</th>
            <th data-field="code">Product Code</th>
            <th data-field="price">Product Name</th>
            <th data-field="unit">Product Count</th>
            <th data-field="edit">Start Time</th>
            <th data-field="edit">End Time</th>
        </tr>
    </thead>
    <tbody>
    <% resources.each do |resource| %>
        <tr>
        <td><%= link_to resource[:campaign_name], campaign_path(resource[:campaign_id]) %></td>
        <td><%= resource[:product_code] %></td>
        <td><%= resource[:product_name] %></td>
        <td><%= resource[:product_count] %></td>
        <td><%= resource[:start_time] %></td>
        <td><%= resource[:end_time] %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate resources %>

app/views/products/_favorite_products.html.erb
<table class="table table-bordered table-condensed table-striped" data-toggle="table">
    <thead>
        <tr>
            <th data-field="name">Product Name</th>
            <th data-field="code">Product Count</th>
        </tr>
    </thead>
    <tbody>
    <% resources.each do |resource| %>
        <tr>
        <td><%= resource[:product_name] %></td>
        <td><%= resource[:product_count] %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate resources %>

app/views/products/_form.html.erb
<%= simple_form_for(product, html: { class: 'form-horizontal' }, method: :put) do |f| %>
  <%= f.input :name %>
  <%= f.input :code %>
  <%= f.input :price %>
  <%= f.input :unit %>
  <%= f.submit :Update, class: "btn btn-primary" %>
<% end %>

app/views/products/_list.html.erb
<table class="table table-bordered table-condensed table-striped" data-toggle="table">
    <thead>
        <tr>
            <th data-field="name">Name</th>
            <th data-field="code">Code</th>
            <th data-field="price">Price</th>
            <th data-field="unit">Unit</th>
            <th data-field="edit">Edit</th>
        </tr>
    </thead>
    <tbody>
    <% resources.each do |product| %>
        <tr>
        <td><%= product.name %></td>
        <td><%= product.code %></td>
        <td><%= product.price %></td>
        <td><%= product.unit %></td>
        <td><i class="fa fa-pencil-square-o" aria-hidden="true" data-toggle="modal" data-target="#form-modal-<%= product.id %>"></i></td>
        <%= render partial: "products/modal_form", locals: { product: product } %>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate resources %>

app/views/products/_modal_form.html.erb
<div class="modal fade" id="form-modal-<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>

                    </button>
                     <h4 class="modal-title" id="myModalLabel">Update Product <%= product.name %></h4>

                </div>
                <div class="modal-body">
                    <%= render partial: "products/form", locals: { product: product } %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/import.html.erb
<h2>Import Products</h2>
<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/products/index.html.erb
<h2>Import Products</h2>
<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<h3>All Products</h3>
<%= render partial: "products/list", locals: { resources: @resources } %>
<br/>
<h3>Campaigns' Products</h3>
<%= render partial: "products/campaign_products", locals: { resources: @campaign_products } %>
<br/>
<h3>Sản phẩm ưa chuộng</h3>
<%= render partial: "products/favorite_products", locals: { resources: @favorite_products } %>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>