config/routes.rb
Rails.application.routes.draw do
  resources :gift_statuses, only: [:index, :create, :find]
  get '/promotion', to: 'gift_statuses#index'
  post '/promotion', to: 'gift_statuses#create'
  post '/find_promotion', to: 'gift_statuses#find'
  resources :products, only: [:index, :new, :create, :update] do 
  	collection do 
  	  post :import
  	end
  end
  resources :users, only: [:index, :new, :create, :update] do 
    collection do 
      post :import_resellers
    end
  end
  resources :customers, only: [:index, :show, :update] do 
  	collection do 
  	  post :import
  	  post :generate_code
      get  :export
      post :approve_all
      post :import_sms
  	end
  end
  resources :campaigns, only: [:index, :new, :create, :edit, :update, :show] do 
    collection do 
      get :cost_report
      get :time_report
    end
  end
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'home#index'
  get '404', :to => 'application#page_not_found'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_form.rb
class BaseForm
  include ActiveModel::Model
  include AppendErrors
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  include CampaignValidator, 
  		  CampaignAssociation, 
  		  CampaignScope
end

app/models/campaign_customer.rb
class CampaignCustomer < ApplicationRecord
  include CampaignCustomerAssociation, 
  		  CampaignCustomerValidator, 
  		  CampaignCustomerScope
end

app/models/campaign_form.rb
class CampaignForm < BaseForm
  
  attr_accessor :name, :content, :start_time, :end_time, :location, :product_count, :product_id

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
  validates :product_count, presence: true, numericality: { greater_than: 0 }
  validates :product_id, presence: true

  def save
  	if valid?
  	  product = Product.find_by_id(product_id)
      start_time = DateTime.parse(start_time) rescue Time.current
      end_time = DateTime.parse(end_time) rescue Time.current
  	  if product
  	  	command = CreateCampaign.call(
  	  	  name, content, start_time, end_time, location, product_count, product
  	  	)
  	  	return command.result if command.success?
  	  	append_errors command
  	  else
  	  	errors.add :campaign_form, "Product not found"
  	  end
  	end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  include CustomerValidator
end

app/models/gift_status_form.rb
class GiftStatusForm < BaseForm

  attr_accessor :phone, :code

  validates :phone, presence: true
  validates :code, presence: true
  validate :check_code
  

  def find 
    result = CampaignCustomerQuery.new.by_phone_and_code(phone, code)
    return result if result
    errors.add :gift_status_form, "No result"
    nil
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include ProductValidator, 
  		  ProductAssociation
end

app/models/session.rb
class Session
  include ActiveModel::Model

  attr_accessor :email, :password

  validates :email, presence: true
  validates :password, presence: true

  def login(session)
  	if valid?
  		command = LoginUser.call(email, password)
  		if command.success?
  			session[:user_id] = command.result.id
  			true
  		else
  			false
  		end
  	end
  end

  def self.check(session)
    self.current_user(session)
  end

  def self.current_user(session)
    return nil unless session[:user_id]
    User.find_by_id(session[:user_id])
  end
end

app/models/user.rb
class User < ApplicationRecord  
  include Authenticable, 
  		  UserScope, 
  		  UserValidator
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login
  layout :home_layout
  
  def index
  end

  private

  def home_layout
  	return "landing" unless logged_in?
  	"application"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin
  before_action :require_user, only: [:update]

  def index
  	@resellers = paginate User.reseller
  end

  def new
  end

  def update
    command = UpdateRecord.call(user, user_params)
    if command.success?
      redirect_to users_path, success: "Updated successfully"
    else
      redirect_to users_path, error: "Update error"
    end
  end

  def create
  end

  def import_resellers
  	import_command = BatchFileImportResellers.call(params[:file])
  	if import_command.success?
  	  redirect_to users_path, notice: "Users successfully imported"
  	else
  	  redirect_to users_path, danger: import_command.errors.to_s
  	end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone, :location)
  end

  def require_user
    @user ||= User.find_by_id(params[:id])
    redirect_to users_path, error: "User not found" and return unless @user
  end

  def user
    @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
	  { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
	end

	def flash_messages(opts = {})
	  flash.each do |msg_type, message|
	    concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
	      concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
	        concat message 
	     end)
	  end
	  nil
	end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gift_statuses_helper.rb
module GiftStatusesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Place sticky footer content here.</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if logged_in? %>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_panel.html.erb
<% if admin? %>
<div class="well">
<%= link_to "Users", users_path, class: "btn btn-primary" %>
-->
<%= link_to "Customers", customers_path, class: "btn btn-primary" %>
-->
<%= link_to "Products", products_path, class: "btn btn-primary" %>
-->
<%= link_to "Campaigns", campaigns_path, class: "btn btn-primary" %>
</div>
<% end %>
<% if reseller? %>
<%= link_to "Check Code", promotion_path, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CCS</title>
    <%= csrf_meta_tags %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDC_f7OaJMYMK92QjscI1B8Jo9U_33bBhQ&libraries=places"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= yield(:css_include) if content_for(:css_include) %>
  </head>

  <body>
  	<%= render "layouts/navbar" %>    
  	<div class="container">
      <%= flash_messages %>
      <%= render "layouts/panel" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
    
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CCS</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'grayscale', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- Theme CSS -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i> <span class="light">Coupon Code</span> System
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download">Features</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <li>
                        <% if logged_in? %>
                          <%= link_to "Logout", logout_path, method: :delete %>
                        <% else %>
                          <%= link_to "Login", login_path %>
                        <% end %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">CCS</h1>
                        <p class="intro-text">A software to manage your coupons
                            <br></p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About CCS</h2>
                <p>CCS is a free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, simply download the template on <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
                <p>This theme features stock photos by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
                <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with LESS files for easy customization.</p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download Grayscale</h2>
                    <p>You can download Grayscale for free on the preview page at Start Bootstrap.</p>
                    <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Download Page</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Start Bootstrap</h2>
                <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                <p><a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <div id="map"></div>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; CCS 2017</p>
        </div>
    </footer>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDC_f7OaJMYMK92QjscI1B8Jo9U_33bBhQ&sensor=false"></script>
    <%= javascript_include_tag 'grayscale', 'data-turbolinks-track': 'reload' %>
    <!-- Theme JavaScript -->
</body>

</html>